-- GENERATED by C->Haskell Compiler, version 0.28.8 Switcheroo, 25 November 2017 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "Doubler.chs" #-}
module Doubler where
import qualified Foreign.C.Types as C2HSImp
import qualified System.IO.Unsafe as C2HSImp



doubleInt :: (Int) -> (Int)
doubleInt a1 =
  C2HSImp.unsafePerformIO $
  let {a1' = fromIntegral a1} in 
  doubleInt'_ a1' >>= \res ->
  let {res' = fromIntegral res} in
  return (res')

{-# LINE 3 "Doubler.chs" #-}


foreign import ccall safe "Doubler.chs.h doubleInt"
  doubleInt'_ :: (C2HSImp.CInt -> (IO C2HSImp.CInt))
