-- GENERATED by C->Haskell Compiler, version 0.28.8 Switcheroo, 25 November 2017 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "test.chs" #-}
module Doubler where
import qualified Foreign.C.Types as C2HSImp



doubleInt :: (Int) -> IO ((Int))
doubleInt a1 =
  let {a1' = input a1} in 
  doubleInt'_ a1' >>= \res ->
  let {res' = fromIntegral res} in
  return (res')

{-# LINE 3 "test.chs" #-}


foreign import ccall safe "test.chs.h doubleInt"
  doubleInt'_ :: (C2HSImp.CInt -> (IO C2HSImp.CInt))
